@tool
class_name Level
extends Node2D

## One room, built around one painted map in descent/assets/maps/.
##
## `kind` is the load-bearing field. A FLAT level is the top-down chamber the
## game has always used: the player is clamped inside `WalkableRegion` and there
## is no such thing as falling. A VERTICAL level is seen from the side — the
## floor exists only where a `LevelPlatform` says it does, and everything under
## the lowest one is a `DeathZone`.
##
## Positions are authored in the map's own pixel space (1536x1024, origin at the
## background's top-left), so a coordinate here is the same coordinate you would
## measure in an image editor. `LevelHost` handles fitting that to the viewport.
##
## Node tree:
##
##   Level
##   ├── Background       Sprite2D, top-left anchored, the map PNG
##   ├── Walls            StaticBody2D, group "walls" — the room's outer frame
##   ├── Platforms        LevelPlatform children (VERTICAL only)
##   ├── Hazards          HazardZone children — lava, sludge, arcane vents
##   ├── DeathZones       DeathZone children (VERTICAL only)
##   ├── WalkableRegion   Area2D, the clamp rect (FLAT only)
##   ├── PlayerStart      Marker2D
##   ├── SpawnPoints      Marker2D children
##
## Generated by tools/gen_levels.py from the map art. Re-running that discards
## hand edits unless the level has been marked `reviewed`.

enum Kind {
	## Top-down chamber: the player is clamped to a floor rect and cannot fall.
	FLAT,
	## Side-on room with platforms, gaps, and a killing fall.
	VERTICAL,
}

## Named HazardKind, not Hazard, because `Hazard` is already the global class for
## the runtime-spawned eruption.
enum HazardKind {
	LAVA,
	FROST,
	POISON,
	DROWNING,
	ARCANE,
	THORNS,
	VOID,
	MOLTEN_GOLD,
	MACHINERY,
	SHOCK,
}

@export var kind: Kind = Kind.FLAT:
	set(value):
		kind = value
		update_configuration_warnings()

@export var hazard_kind: HazardKind = HazardKind.LAVA

@export var display_name: String = ""

## Theme token from the map filename: fire, ice, poison, water, crystal, nature,
## shadow, gold, clockwork, electric.
@export var theme: String = ""

## Untick until a human has opened this level and checked the generated
## platforms, hazards, and spawns against the art. Generated levels start false.
@export var reviewed: bool = false:
	set(value):
		reviewed = value
		update_configuration_warnings()

## The map's pixel dimensions, and therefore this level's own coordinate space.
@export var content_size: Vector2 = Vector2(1536, 1024)

@onready var _platforms: Node2D = $Platforms
@onready var _hazards: Node2D = $Hazards
@onready var _death_zones: Node2D = $DeathZones
@onready var _walkable: Area2D = $WalkableRegion
@onready var _player_start: Marker2D = $PlayerStart
@onready var _spawn_points: Node2D = $SpawnPoints


func _ready() -> void:
	# Hybrid maps that currently fall back to their WalkableRegion keep their
	# authored pit for later platform conversion, but it must not kill a
	# top-down actor clamped to the edge of that region.
	if kind == Kind.VERTICAL and not is_vertical():
		for zone in death_zones():
			zone.monitoring = false
			zone.monitorable = false


## The handles above stay null until the level enters the tree, but the editor
## and the level tooling both read a level right after instantiating it, so
## every accessor resolves through here instead of trusting the cache.
func _branch(cached: Node, branch_name: String) -> Node:
	return cached if cached != null else get_node_or_null(branch_name)


func is_vertical() -> bool:
	if kind != Kind.VERTICAL:
		return false
	var marker := _branch(_player_start, "PlayerStart") as Marker2D
	if marker == null:
		return false
	# A few maps carry the vertical filename/metadata but their actual authored
	# floor is still a WalkableRegion. Treat those as top-down until matching
	# LevelPlatform collision is added, rather than dropping actors into air.
	for platform in platforms():
		var surface_y := platform.surface_y_at(marker.position.x, 24.0)
		if not is_inf(surface_y) and absf((surface_y - 22.0) - marker.position.y) <= 120.0:
			return true
	return false


## The rectangle a top-down actor is clamped inside. Vertical levels have no
## such rect — gravity and the platforms decide where you can be — so they
## report their full content box and callers should check `is_vertical()` first.
func walkable_bounds() -> Rect2:
	var walkable := _branch(_walkable, "WalkableRegion")
	if is_vertical() or walkable == null:
		return Rect2(Vector2.ZERO, content_size)
	var combined := Rect2()
	var found_shape := false
	for child in walkable.get_children():
		var shape := child as CollisionShape2D
		if shape == null:
			continue
		var rect := shape.shape as RectangleShape2D
		if rect == null:
			continue
		var scaled_size := Vector2(
			rect.size.x * absf(shape.scale.x),
			rect.size.y * absf(shape.scale.y)
		)
		var center := (walkable as Node2D).position + shape.position
		var shape_bounds := Rect2(center - scaled_size * 0.5, scaled_size)
		combined = combined.merge(shape_bounds) if found_shape else shape_bounds
		found_shape = true
	return combined if found_shape else Rect2(Vector2.ZERO, content_size)


func player_start() -> Vector2:
	var marker := _branch(_player_start, "PlayerStart") as Marker2D
	return marker.position if marker != null else content_size * 0.5


func spawn_positions() -> Array[Vector2]:
	var points: Array[Vector2] = []
	var root := _branch(_spawn_points, "SpawnPoints")
	if root == null:
		return points
	for child in root.get_children():
		if child is Marker2D:
			points.append((child as Marker2D).position)
	return points


func platforms() -> Array[LevelPlatform]:
	var found: Array[LevelPlatform] = []
	var root := _branch(_platforms, "Platforms")
	if root == null:
		return found
	for child in root.get_children():
		if child is LevelPlatform:
			found.append(child as LevelPlatform)
	return found


func hazard_zones() -> Array[HazardZone]:
	var found: Array[HazardZone] = []
	var root := _branch(_hazards, "Hazards")
	if root == null:
		return found
	for child in root.get_children():
		if child is HazardZone:
			found.append(child as HazardZone)
	return found


func death_zones() -> Array[DeathZone]:
	var found: Array[DeathZone] = []
	var root := _branch(_death_zones, "DeathZones")
	if root == null:
		return found
	for child in root.get_children():
		if child is DeathZone:
			found.append(child as DeathZone)
	return found


## Returns the platform directly under an actor centre. The tolerance includes
## the actor radius because authored markers are not all placed at foot level.
func supporting_platform(
	point: Vector2, actor_radius: float = 20.0, max_distance: float = 42.0
) -> LevelPlatform:
	var nearest: LevelPlatform = null
	var nearest_distance := INF
	for platform in platforms():
		var surface_y := platform.surface_y_at(point.x, actor_radius * 0.35)
		if is_inf(surface_y):
			continue
		var distance := surface_y - point.y
		if distance < -actor_radius or distance > max_distance + actor_radius:
			continue
		if absf(distance) < nearest_distance:
			nearest = platform
			nearest_distance = absf(distance)
	return nearest


func platforms_share_route(a: LevelPlatform, b: LevelPlatform) -> bool:
	if a == null or b == null:
		return false
	if a == b:
		return true
	if not a.traversal_group.is_empty() and a.traversal_group == b.traversal_group:
		return true
	return false


## Breadth-first platform graph search. Edges exist only between authored stair
## pieces or platforms that overlap horizontally, so monsters never invent a
## diagonal shortcut across a pit. The returned platform is the next hop.
func next_platform_toward(
	start: LevelPlatform,
	goal: LevelPlatform,
	min_overlap: float,
	max_jump_height: float,
	max_drop_height: float = 360.0
) -> LevelPlatform:
	if start == null or goal == null:
		return null
	if platforms_share_route(start, goal):
		return goal

	var queue: Array[LevelPlatform] = [start]
	var came_from: Dictionary = {start: null}
	var cursor := 0
	while cursor < queue.size():
		var current := queue[cursor]
		cursor += 1
		for candidate in platforms():
			if came_from.has(candidate) or candidate == current:
				continue
			if not _platforms_are_navigable(
				current, candidate, min_overlap, max_jump_height, max_drop_height
			):
				continue
			came_from[candidate] = current
			if candidate == goal:
				var step := goal
				while came_from[step] != start:
					step = came_from[step] as LevelPlatform
				return step
			queue.append(candidate)
	return null


func _platforms_are_navigable(
	from: LevelPlatform,
	to: LevelPlatform,
	min_overlap: float,
	max_jump_height: float,
	max_drop_height: float
) -> bool:
	if platforms_share_route(from, to):
		return true
	var from_range := from.navigation_x_range()
	var to_range := to.navigation_x_range()
	var left := maxf(from_range.x, to_range.x)
	var right := minf(from_range.y, to_range.y)
	if right - left < min_overlap:
		return false
	var sample_x := (left + right) * 0.5
	var from_y := from.surface_y_at(sample_x, 1.0)
	var to_y := to.surface_y_at(sample_x, 1.0)
	if is_inf(from_y) or is_inf(to_y):
		return false
	var rise := from_y - to_y
	return (
		(rise >= 0.0 and rise <= max_jump_height)
		or (rise < 0.0 and -rise <= max_drop_height)
	)


## Used by enemy edge avoidance. A support may be a short step below the
## current floor, but never an unbounded pit.
func has_support_below(
	x: float, actor_y: float, max_drop: float = 70.0, ignored: LevelPlatform = null
) -> bool:
	for platform in platforms():
		if platform == ignored:
			continue
		var surface_y := platform.surface_y_at(x, 4.0)
		if is_inf(surface_y):
			continue
		if surface_y >= actor_y - 10.0 and surface_y <= actor_y + max_drop:
			return true
	return false


func is_hazardous(point: Vector2, margin: float = 20.0) -> bool:
	for hazard in hazard_zones():
		var rect := Rect2(hazard.position - hazard.size * 0.5, hazard.size).grow(margin)
		if rect.has_point(point):
			return true
	for death_zone in death_zones():
		var rect := Rect2(
			death_zone.position - death_zone.size * 0.5, death_zone.size
		).grow(margin)
		if rect.has_point(point):
			return true
	return false


## Safe centre bounds inside the authored outer wall collision. Content bounds
## alone include the thickness of those walls, which allowed large monsters to
## appear partly inside or beyond the room frame.
func spawn_bounds(actor_radius: float = 20.0) -> Rect2:
	var safe := Rect2(Vector2.ZERO, content_size).grow(-actor_radius)
	var walls := get_node_or_null("Walls") as Node2D
	if walls == null:
		return safe

	var left := safe.position.x
	var top := safe.position.y
	var right := safe.end.x
	var bottom := safe.end.y
	for child in walls.get_children():
		var shape := child as CollisionShape2D
		if shape == null:
			continue
		var rectangle := shape.shape as RectangleShape2D
		if rectangle == null:
			continue
		var scale_x := shape.global_transform.x.length()
		var scale_y := shape.global_transform.y.length()
		var size := Vector2(rectangle.size.x * scale_x, rectangle.size.y * scale_y)
		var center := to_local(shape.global_position)
		if size.y >= content_size.y * 0.5:
			if center.x < content_size.x * 0.5:
				left = maxf(left, center.x + size.x * 0.5 + actor_radius)
			else:
				right = minf(right, center.x - size.x * 0.5 - actor_radius)
		elif size.x >= content_size.x * 0.5:
			if center.y < content_size.y * 0.5:
				top = maxf(top, center.y + size.y * 0.5 + actor_radius)
			else:
				bottom = minf(bottom, center.y - size.y * 0.5 - actor_radius)
	return Rect2(Vector2(left, top), Vector2(maxf(0.0, right - left), maxf(0.0, bottom - top)))


func is_safe_spawn(point: Vector2, actor_radius: float = 20.0) -> bool:
	var bounds := spawn_bounds(actor_radius)
	if not bounds.has_point(point) or is_hazardous(point, actor_radius):
		return false
	if not is_vertical():
		return walkable_bounds().grow(-actor_radius).has_point(point) \
			and not is_blocked(point, actor_radius)
	return supporting_platform(point, actor_radius, 55.0) != null


## Snaps an authored or generated point to the nearest safe floor. Returning
## Vector2.INF lets callers reject a room/marker instead of spawning over a pit.
func safe_spawn_position(preferred: Vector2, actor_radius: float = 20.0) -> Vector2:
	if not is_vertical():
		var bounds := walkable_bounds().grow(-actor_radius).intersection(
			spawn_bounds(actor_radius)
		)
		if bounds.size.x <= 0.0 or bounds.size.y <= 0.0:
			return Vector2.INF
		var clamped := Vector2(
			clampf(preferred.x, bounds.position.x, bounds.end.x),
			clampf(preferred.y, bounds.position.y, bounds.end.y)
		)
		if is_safe_spawn(clamped, actor_radius):
			return clamped
		for marker in spawn_positions():
			if is_safe_spawn(marker, actor_radius):
				return marker
		return Vector2.INF

	var best := Vector2.INF
	var best_score := INF
	for platform in platforms():
		var x_range := platform.navigation_x_range()
		var candidate_x := (x_range.x + x_range.y) * 0.5
		if x_range.y - x_range.x >= actor_radius * 2.0:
			candidate_x = clampf(
				preferred.x,
				x_range.x + actor_radius,
				x_range.y - actor_radius
			)
		var surface_y := platform.surface_y_at(candidate_x, 1.0)
		if is_inf(surface_y):
			continue
		var candidate := Vector2(candidate_x, surface_y - actor_radius - 2.0)
		if is_hazardous(candidate, actor_radius):
			continue
		var content_bounds := spawn_bounds(actor_radius)
		if not content_bounds.has_point(candidate):
			continue
		var score := candidate.distance_squared_to(preferred)
		if score < best_score:
			best = candidate
			best_score = score
	return best


## True when the point is inside a platform, used to keep enemy spawns from
## being placed inside a ledge.
func is_blocked(point: Vector2, margin: float = 24.0) -> bool:
	for platform in platforms():
		var rect := Rect2(platform.position - platform.size * 0.5, platform.size)
		if rect.grow(margin).has_point(point):
			return true
	return false


func _get_configuration_warnings() -> PackedStringArray:
	var warnings := PackedStringArray()
	if not reviewed:
		warnings.append("Generated from the map art and not reviewed yet.")
	if kind != Kind.VERTICAL:
		return warnings

	var platform_root := get_node_or_null("Platforms")
	if platform_root != null and platform_root.get_child_count() == 0:
		warnings.append("Vertical level has no platforms; nothing is standable.")
	var death_root := get_node_or_null("DeathZones")
	if death_root != null and death_root.get_child_count() == 0:
		warnings.append("Vertical level has no death zone under the platforms.")
	return warnings
