@tool
class_name Level
extends Node2D

## One room, built around one painted map in descent/assets/maps/.
##
## `kind` is the load-bearing field. A FLAT level is the top-down chamber the
## game has always used: the player is clamped inside `WalkableRegion` and there
## is no such thing as falling. A VERTICAL level is seen from the side — the
## floor exists only where a `LevelPlatform` says it does, and everything under
## the lowest one is a `DeathZone`.
##
## Positions are authored in the map's own pixel space (1536x1024, origin at the
## background's top-left), so a coordinate here is the same coordinate you would
## measure in an image editor. `LevelHost` handles fitting that to the viewport.
##
## Node tree:
##
##   Level
##   ├── Background       Sprite2D, top-left anchored, the map PNG
##   ├── Walls            StaticBody2D, group "walls" — the room's outer frame
##   ├── Platforms        LevelPlatform children (VERTICAL only)
##   ├── Hazards          HazardZone children — lava, sludge, arcane vents
##   ├── DeathZones       DeathZone children (VERTICAL only)
##   ├── WalkableRegion   Area2D, the clamp rect (FLAT only)
##   ├── PlayerStart      Marker2D
##   ├── SpawnPoints      Marker2D children
##   └── DoorAnchors      Loot / Danger / Shop Marker2D
##
## Generated by tools/gen_levels.py from the map art. Re-running that discards
## hand edits unless the level has been marked `reviewed`.

enum Kind {
	## Top-down chamber: the player is clamped to a floor rect and cannot fall.
	FLAT,
	## Side-on room with platforms, gaps, and a killing fall.
	VERTICAL,
}

## Named HazardKind, not Hazard, because `Hazard` is already the global class for
## the runtime-spawned eruption.
enum HazardKind {
	LAVA,
	FROST,
	POISON,
	DROWNING,
	ARCANE,
	THORNS,
	VOID,
	MOLTEN_GOLD,
	MACHINERY,
	SHOCK,
}

@export var kind: Kind = Kind.FLAT:
	set(value):
		kind = value
		update_configuration_warnings()

@export var hazard_kind: HazardKind = HazardKind.LAVA

@export var display_name: String = ""

## Theme token from the map filename: fire, ice, poison, water, crystal, nature,
## shadow, gold, clockwork, electric.
@export var theme: String = ""

## Untick until a human has opened this level and checked the generated
## platforms, hazards, and spawns against the art. Generated levels start false.
@export var reviewed: bool = false:
	set(value):
		reviewed = value
		update_configuration_warnings()

## The map's pixel dimensions, and therefore this level's own coordinate space.
@export var content_size: Vector2 = Vector2(1536, 1024)

@onready var _platforms: Node2D = $Platforms
@onready var _hazards: Node2D = $Hazards
@onready var _death_zones: Node2D = $DeathZones
@onready var _walkable: Area2D = $WalkableRegion
@onready var _player_start: Marker2D = $PlayerStart
@onready var _spawn_points: Node2D = $SpawnPoints


## The handles above stay null until the level enters the tree, but the editor
## and the level tooling both read a level right after instantiating it, so
## every accessor resolves through here instead of trusting the cache.
func _branch(cached: Node, branch_name: String) -> Node:
	return cached if cached != null else get_node_or_null(branch_name)


func is_vertical() -> bool:
	return kind == Kind.VERTICAL


## The rectangle a top-down actor is clamped inside. Vertical levels have no
## such rect — gravity and the platforms decide where you can be — so they
## report their full content box and callers should check `is_vertical()` first.
func walkable_bounds() -> Rect2:
	var walkable := _branch(_walkable, "WalkableRegion")
	if is_vertical() or walkable == null:
		return Rect2(Vector2.ZERO, content_size)
	var shape := walkable.get_node_or_null("Shape") as CollisionShape2D
	if shape == null:
		return Rect2(Vector2.ZERO, content_size)
	var rect := shape.shape as RectangleShape2D
	if rect == null:
		return Rect2(Vector2.ZERO, content_size)
	return Rect2((walkable as Node2D).position - rect.size * 0.5, rect.size)


func player_start() -> Vector2:
	var marker := _branch(_player_start, "PlayerStart") as Marker2D
	return marker.position if marker != null else content_size * 0.5


func spawn_positions() -> Array[Vector2]:
	var points: Array[Vector2] = []
	var root := _branch(_spawn_points, "SpawnPoints")
	if root == null:
		return points
	for child in root.get_children():
		if child is Marker2D:
			points.append((child as Marker2D).position)
	return points


## Where an exit door belongs, by node name under DoorAnchors. Returns
## Vector2.INF when this level does not define that anchor, so the caller can
## tell "not authored" apart from "authored at the origin".
func door_anchor(door_name: StringName) -> Vector2:
	var anchors := get_node_or_null("DoorAnchors")
	if anchors == null:
		return Vector2.INF
	var marker := anchors.get_node_or_null(NodePath(door_name)) as Marker2D
	return marker.position if marker != null else Vector2.INF


func platforms() -> Array[LevelPlatform]:
	var found: Array[LevelPlatform] = []
	var root := _branch(_platforms, "Platforms")
	if root == null:
		return found
	for child in root.get_children():
		if child is LevelPlatform:
			found.append(child as LevelPlatform)
	return found


func hazard_zones() -> Array[HazardZone]:
	var found: Array[HazardZone] = []
	var root := _branch(_hazards, "Hazards")
	if root == null:
		return found
	for child in root.get_children():
		if child is HazardZone:
			found.append(child as HazardZone)
	return found


func death_zones() -> Array[DeathZone]:
	var found: Array[DeathZone] = []
	var root := _branch(_death_zones, "DeathZones")
	if root == null:
		return found
	for child in root.get_children():
		if child is DeathZone:
			found.append(child as DeathZone)
	return found


## True when the point is inside a platform, used to keep enemy spawns from
## being placed inside a ledge.
func is_blocked(point: Vector2, margin: float = 24.0) -> bool:
	for platform in platforms():
		var rect := Rect2(platform.position - platform.size * 0.5, platform.size)
		if rect.grow(margin).has_point(point):
			return true
	return false


func _get_configuration_warnings() -> PackedStringArray:
	var warnings := PackedStringArray()
	if not reviewed:
		warnings.append("Generated from the map art and not reviewed yet.")
	if kind != Kind.VERTICAL:
		return warnings

	var platform_root := get_node_or_null("Platforms")
	if platform_root != null and platform_root.get_child_count() == 0:
		warnings.append("Vertical level has no platforms; nothing is standable.")
	var death_root := get_node_or_null("DeathZones")
	if death_root != null and death_root.get_child_count() == 0:
		warnings.append("Vertical level has no death zone under the platforms.")
	return warnings
